user:
    resource: "@UserBundle/Resources/config/routing.php"
    prefix:   /

auth:
    resource: "@AuthBundle/Resources/config/routing.php"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
